# Header
menu:
  Home: /
  Bahn: /bahn
  Workshops: /workshops
  Events: /events
  Location: /location
  About us: /about-us
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
sidebar: right
widgets:
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
